/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTimesheetRouteImport } from './routes/_authenticated.timesheet'
import { Route as AuthenticatedResourcesRouteImport } from './routes/_authenticated.resources'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated.projects'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated.profile'
import { Route as AuthenticatedInvoicesRouteImport } from './routes/_authenticated.invoices'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated.clients'
import { Route as AuthenticatedResourcesIdRouteImport } from './routes/_authenticated.resources.$id'
import { Route as AuthenticatedProjectsIdRouteImport } from './routes/_authenticated.projects.$id'
import { Route as AuthenticatedClientsIdRouteImport } from './routes/_authenticated.clients.$id'
import { Route as AuthenticatedAnalyticsUtilizationRouteImport } from './routes/_authenticated.analytics.utilization'
import { Route as AuthenticatedAnalyticsReportsRouteImport } from './routes/_authenticated.analytics.reports'
import { Route as AuthenticatedAnalyticsPortfolioRouteImport } from './routes/_authenticated.analytics.portfolio'
import { Route as AuthenticatedAdminMasterDataRouteImport } from './routes/_authenticated.admin.master-data'
import { Route as AuthenticatedAdminLookupsRouteImport } from './routes/_authenticated.admin.lookups'
import { Route as AuthenticatedAdminLookupsLookupIdRouteImport } from './routes/_authenticated.admin.lookups.$lookupId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTimesheetRoute = AuthenticatedTimesheetRouteImport.update({
  id: '/timesheet',
  path: '/timesheet',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedResourcesRoute = AuthenticatedResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInvoicesRoute = AuthenticatedInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedResourcesIdRoute =
  AuthenticatedResourcesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedResourcesRoute,
  } as any)
const AuthenticatedProjectsIdRoute = AuthenticatedProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedProjectsRoute,
} as any)
const AuthenticatedClientsIdRoute = AuthenticatedClientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedClientsRoute,
} as any)
const AuthenticatedAnalyticsUtilizationRoute =
  AuthenticatedAnalyticsUtilizationRouteImport.update({
    id: '/analytics/utilization',
    path: '/analytics/utilization',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAnalyticsReportsRoute =
  AuthenticatedAnalyticsReportsRouteImport.update({
    id: '/analytics/reports',
    path: '/analytics/reports',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAnalyticsPortfolioRoute =
  AuthenticatedAnalyticsPortfolioRouteImport.update({
    id: '/analytics/portfolio',
    path: '/analytics/portfolio',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminMasterDataRoute =
  AuthenticatedAdminMasterDataRouteImport.update({
    id: '/admin/master-data',
    path: '/admin/master-data',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminLookupsRoute =
  AuthenticatedAdminLookupsRouteImport.update({
    id: '/admin/lookups',
    path: '/admin/lookups',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminLookupsLookupIdRoute =
  AuthenticatedAdminLookupsLookupIdRouteImport.update({
    id: '/$lookupId',
    path: '/$lookupId',
    getParentRoute: () => AuthenticatedAdminLookupsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clients': typeof AuthenticatedClientsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/resources': typeof AuthenticatedResourcesRouteWithChildren
  '/timesheet': typeof AuthenticatedTimesheetRoute
  '/admin/lookups': typeof AuthenticatedAdminLookupsRouteWithChildren
  '/admin/master-data': typeof AuthenticatedAdminMasterDataRoute
  '/analytics/portfolio': typeof AuthenticatedAnalyticsPortfolioRoute
  '/analytics/reports': typeof AuthenticatedAnalyticsReportsRoute
  '/analytics/utilization': typeof AuthenticatedAnalyticsUtilizationRoute
  '/clients/$id': typeof AuthenticatedClientsIdRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/resources/$id': typeof AuthenticatedResourcesIdRoute
  '/admin/lookups/$lookupId': typeof AuthenticatedAdminLookupsLookupIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clients': typeof AuthenticatedClientsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/resources': typeof AuthenticatedResourcesRouteWithChildren
  '/timesheet': typeof AuthenticatedTimesheetRoute
  '/admin/lookups': typeof AuthenticatedAdminLookupsRouteWithChildren
  '/admin/master-data': typeof AuthenticatedAdminMasterDataRoute
  '/analytics/portfolio': typeof AuthenticatedAnalyticsPortfolioRoute
  '/analytics/reports': typeof AuthenticatedAnalyticsReportsRoute
  '/analytics/utilization': typeof AuthenticatedAnalyticsUtilizationRoute
  '/clients/$id': typeof AuthenticatedClientsIdRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/resources/$id': typeof AuthenticatedResourcesIdRoute
  '/admin/lookups/$lookupId': typeof AuthenticatedAdminLookupsLookupIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/invoices': typeof AuthenticatedInvoicesRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/_authenticated/resources': typeof AuthenticatedResourcesRouteWithChildren
  '/_authenticated/timesheet': typeof AuthenticatedTimesheetRoute
  '/_authenticated/admin/lookups': typeof AuthenticatedAdminLookupsRouteWithChildren
  '/_authenticated/admin/master-data': typeof AuthenticatedAdminMasterDataRoute
  '/_authenticated/analytics/portfolio': typeof AuthenticatedAnalyticsPortfolioRoute
  '/_authenticated/analytics/reports': typeof AuthenticatedAnalyticsReportsRoute
  '/_authenticated/analytics/utilization': typeof AuthenticatedAnalyticsUtilizationRoute
  '/_authenticated/clients/$id': typeof AuthenticatedClientsIdRoute
  '/_authenticated/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/_authenticated/resources/$id': typeof AuthenticatedResourcesIdRoute
  '/_authenticated/admin/lookups/$lookupId': typeof AuthenticatedAdminLookupsLookupIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/clients'
    | '/dashboard'
    | '/invoices'
    | '/profile'
    | '/projects'
    | '/resources'
    | '/timesheet'
    | '/admin/lookups'
    | '/admin/master-data'
    | '/analytics/portfolio'
    | '/analytics/reports'
    | '/analytics/utilization'
    | '/clients/$id'
    | '/projects/$id'
    | '/resources/$id'
    | '/admin/lookups/$lookupId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/clients'
    | '/dashboard'
    | '/invoices'
    | '/profile'
    | '/projects'
    | '/resources'
    | '/timesheet'
    | '/admin/lookups'
    | '/admin/master-data'
    | '/analytics/portfolio'
    | '/analytics/reports'
    | '/analytics/utilization'
    | '/clients/$id'
    | '/projects/$id'
    | '/resources/$id'
    | '/admin/lookups/$lookupId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/clients'
    | '/_authenticated/dashboard'
    | '/_authenticated/invoices'
    | '/_authenticated/profile'
    | '/_authenticated/projects'
    | '/_authenticated/resources'
    | '/_authenticated/timesheet'
    | '/_authenticated/admin/lookups'
    | '/_authenticated/admin/master-data'
    | '/_authenticated/analytics/portfolio'
    | '/_authenticated/analytics/reports'
    | '/_authenticated/analytics/utilization'
    | '/_authenticated/clients/$id'
    | '/_authenticated/projects/$id'
    | '/_authenticated/resources/$id'
    | '/_authenticated/admin/lookups/$lookupId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/timesheet': {
      id: '/_authenticated/timesheet'
      path: '/timesheet'
      fullPath: '/timesheet'
      preLoaderRoute: typeof AuthenticatedTimesheetRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/resources': {
      id: '/_authenticated/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof AuthenticatedResourcesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invoices': {
      id: '/_authenticated/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthenticatedInvoicesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/resources/$id': {
      id: '/_authenticated/resources/$id'
      path: '/$id'
      fullPath: '/resources/$id'
      preLoaderRoute: typeof AuthenticatedResourcesIdRouteImport
      parentRoute: typeof AuthenticatedResourcesRoute
    }
    '/_authenticated/projects/$id': {
      id: '/_authenticated/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AuthenticatedProjectsIdRouteImport
      parentRoute: typeof AuthenticatedProjectsRoute
    }
    '/_authenticated/clients/$id': {
      id: '/_authenticated/clients/$id'
      path: '/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof AuthenticatedClientsIdRouteImport
      parentRoute: typeof AuthenticatedClientsRoute
    }
    '/_authenticated/analytics/utilization': {
      id: '/_authenticated/analytics/utilization'
      path: '/analytics/utilization'
      fullPath: '/analytics/utilization'
      preLoaderRoute: typeof AuthenticatedAnalyticsUtilizationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics/reports': {
      id: '/_authenticated/analytics/reports'
      path: '/analytics/reports'
      fullPath: '/analytics/reports'
      preLoaderRoute: typeof AuthenticatedAnalyticsReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics/portfolio': {
      id: '/_authenticated/analytics/portfolio'
      path: '/analytics/portfolio'
      fullPath: '/analytics/portfolio'
      preLoaderRoute: typeof AuthenticatedAnalyticsPortfolioRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/master-data': {
      id: '/_authenticated/admin/master-data'
      path: '/admin/master-data'
      fullPath: '/admin/master-data'
      preLoaderRoute: typeof AuthenticatedAdminMasterDataRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/lookups': {
      id: '/_authenticated/admin/lookups'
      path: '/admin/lookups'
      fullPath: '/admin/lookups'
      preLoaderRoute: typeof AuthenticatedAdminLookupsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/lookups/$lookupId': {
      id: '/_authenticated/admin/lookups/$lookupId'
      path: '/$lookupId'
      fullPath: '/admin/lookups/$lookupId'
      preLoaderRoute: typeof AuthenticatedAdminLookupsLookupIdRouteImport
      parentRoute: typeof AuthenticatedAdminLookupsRoute
    }
  }
}

interface AuthenticatedClientsRouteChildren {
  AuthenticatedClientsIdRoute: typeof AuthenticatedClientsIdRoute
}

const AuthenticatedClientsRouteChildren: AuthenticatedClientsRouteChildren = {
  AuthenticatedClientsIdRoute: AuthenticatedClientsIdRoute,
}

const AuthenticatedClientsRouteWithChildren =
  AuthenticatedClientsRoute._addFileChildren(AuthenticatedClientsRouteChildren)

interface AuthenticatedProjectsRouteChildren {
  AuthenticatedProjectsIdRoute: typeof AuthenticatedProjectsIdRoute
}

const AuthenticatedProjectsRouteChildren: AuthenticatedProjectsRouteChildren = {
  AuthenticatedProjectsIdRoute: AuthenticatedProjectsIdRoute,
}

const AuthenticatedProjectsRouteWithChildren =
  AuthenticatedProjectsRoute._addFileChildren(
    AuthenticatedProjectsRouteChildren,
  )

interface AuthenticatedResourcesRouteChildren {
  AuthenticatedResourcesIdRoute: typeof AuthenticatedResourcesIdRoute
}

const AuthenticatedResourcesRouteChildren: AuthenticatedResourcesRouteChildren =
  {
    AuthenticatedResourcesIdRoute: AuthenticatedResourcesIdRoute,
  }

const AuthenticatedResourcesRouteWithChildren =
  AuthenticatedResourcesRoute._addFileChildren(
    AuthenticatedResourcesRouteChildren,
  )

interface AuthenticatedAdminLookupsRouteChildren {
  AuthenticatedAdminLookupsLookupIdRoute: typeof AuthenticatedAdminLookupsLookupIdRoute
}

const AuthenticatedAdminLookupsRouteChildren: AuthenticatedAdminLookupsRouteChildren =
  {
    AuthenticatedAdminLookupsLookupIdRoute:
      AuthenticatedAdminLookupsLookupIdRoute,
  }

const AuthenticatedAdminLookupsRouteWithChildren =
  AuthenticatedAdminLookupsRoute._addFileChildren(
    AuthenticatedAdminLookupsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInvoicesRoute: typeof AuthenticatedInvoicesRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRouteWithChildren
  AuthenticatedResourcesRoute: typeof AuthenticatedResourcesRouteWithChildren
  AuthenticatedTimesheetRoute: typeof AuthenticatedTimesheetRoute
  AuthenticatedAdminLookupsRoute: typeof AuthenticatedAdminLookupsRouteWithChildren
  AuthenticatedAdminMasterDataRoute: typeof AuthenticatedAdminMasterDataRoute
  AuthenticatedAnalyticsPortfolioRoute: typeof AuthenticatedAnalyticsPortfolioRoute
  AuthenticatedAnalyticsReportsRoute: typeof AuthenticatedAnalyticsReportsRoute
  AuthenticatedAnalyticsUtilizationRoute: typeof AuthenticatedAnalyticsUtilizationRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedClientsRoute: AuthenticatedClientsRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInvoicesRoute: AuthenticatedInvoicesRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRouteWithChildren,
  AuthenticatedResourcesRoute: AuthenticatedResourcesRouteWithChildren,
  AuthenticatedTimesheetRoute: AuthenticatedTimesheetRoute,
  AuthenticatedAdminLookupsRoute: AuthenticatedAdminLookupsRouteWithChildren,
  AuthenticatedAdminMasterDataRoute: AuthenticatedAdminMasterDataRoute,
  AuthenticatedAnalyticsPortfolioRoute: AuthenticatedAnalyticsPortfolioRoute,
  AuthenticatedAnalyticsReportsRoute: AuthenticatedAnalyticsReportsRoute,
  AuthenticatedAnalyticsUtilizationRoute:
    AuthenticatedAnalyticsUtilizationRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
